sudo: required

services:
  - docker

language: python

python: 3.6

env:
  global:
    - TOX_ENV=py36

before_install:
  - docker-compose -v
  - docker -v

script:
  - tox
  - sh tests/test_docker.sh

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
