sudo: required

services:
  - docker

language: python

python: 3.6

before_install:
  - docker-compose -v
  - docker -v

script:
  - sh tests/test_docker.sh

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
